version: '3.8'

services:
  mongo:
    image: mongo
    container_name: mongo
    ports:
      - "27017:27017"
    networks:
      - ca2-network

backend:
  image: recipe-backend:latest
  build: ../ead-ca2-BE
  ports:
    - "9090:9090"
  environment:
    DB_URI: mongodb://mongo:27017
    DB_NAME: ead_ca2
    DB_COLLECTION: ead_2024
  depends_on:
    - mongo
  networks:
    - ca2-network

networks:
  ca2-network:
