version: '3.8'

services:
  mongo:
    image: mongo
    container_name: mongo
    ports:
      - "27017:27017"
    networks:
      - app-network

  backend:
    image: recipe-backend:latest
    container_name: backend
    ports:
      - "8080:8080"
    depends_on:
      - mongo
    networks:
      - app-network

networks:
  app-network:
